### PR TITLE
Fix Hash#symbolize_keys conflicts

### PR DESCRIPTION
**Pull request by tardate**
Propono includes a monkey patch of the core Hash class to add #symbolize_keys.

This can causes issues when Propono is added to Rails, or any ActiveSupport-based project, since the Propono version of #symbolize_keys has different behaviour.

To avoid changing Propono behaviour, or needing to add another gem dependency, while also eliminating this compatibility issue,  57d7ff7 moves symbolize_keys to the Propono namespace.

This should not affect existing uses of propono, *unless* they are inheriting Hash#symbolise_keys from Propono and using elsewhere in their projects. They would need to decide to use another library for symbolize_keys, or use Propono::Utils.symbolize_keys explicitly.

A couple of other minor improvements are included in this PR as separate commits.

### CODE REVIEW

**Comment by iHiD** [comment]
@tardate Brilliant. Thanks for this. I'll have a look at it tomorrow :blue_heart: 

@ccare - could you just give it a quick smoke test when you've beaten the lurgy please :)

**Comment by tardate** [comment]
Hi @iHiD , @ccare  .. had a chance to check this out yet? Be nice to see it in the next propono release

**Comment by pnicholls** [comment]
Any news on this @iHiD, @ccare?

**Comment by iHiD** [comment]
Hi @pnicholls, @tardate. So sorry for the delay. I'll get this sorted in the next day or two. Sorry!

**Comment by iHiD** [comment]
@tardate Merged and released in 1.4.0. Sorry again for the delay, and thank you for your contribution. I promise your next one will be dealt with much quicker!! :blue_heart::yellow_heart::purple_heart::heart::green_heart:

(cc @pnicholls @ccare)

**Pull request merged**
